package Elearn::Model::E_learning::ElearnDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Elearn::Schema::E_learning::ElearnDB',
    
    connect_info => {
        dsn => 'dbi:mysql:E_Learning',
        user => 'elearn',
        password => '',
        AutoCommit => q{1},
    }
);

=head1 NAME

Elearn::Model::E_learning::ElearnDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Elearn>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Elearn::Schema::E_learning::ElearnDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

Alvin

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
