---
abstract: 'Catalyst based application'
author:
  - Alvin,,,
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Elearn
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80022
  Config::General: 0
  File::Basename: 0
  File::Copy: 0
  File::HomeDir: 0
  Gtk2::Notify: 0
  JSON: 0
  List::Utils: 0
  Moose: 0
  WWW::Mechanize: 0
  YAML::XS: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
